# Generated by Django 3.0.5 on 2020-04-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(default=350, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=3, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garage',
            field=models.IntegerField(default=1, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_for',
            field=models.CharField(choices=[('SA', 'برای فروش'), ('RE', 'برای اجاره')], default='SA', max_length=2, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='آیا منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=4500000, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_of_property',
            field=models.CharField(choices=[('HO', 'خانه'), ('VI', 'ویلا'), ('SH', 'مغازه'), ('AP', 'آپارتمان'), ('OF', 'دفترکار')], default='HO', max_length=2, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_of_built',
            field=models.IntegerField(default=1395, verbose_name='سال ساخت'),
        ),
    ]
